export const TEAM = [
  {
    id: "john-mark",
    name: "John Mark",
    role: "Backend & Systems Architecture",
    bio: "Specializing in robust backend infrastructure and 3D web integration. Lead architect on multi-admin CMS platforms and high-traffic survey systems.",
    techStack: ["FastAPI", "ReactJS", "PostgreSQL", "C# ASP.NET", "SignalR"],
    colorA: "#2E5BFF",
    colorB: "#6366F1",
    position: [-4, 0, 0],
    website: "https://yuehan.yhubkeysystem.site",
  },
  {
    id: "member-2",
    name: "Member 2",
    role: "Full-Stack Developer",
    bio: "Bridging the gap between server logic and interactive front-end experiences. Co-developer of seamless digital ecosystems.",
    techStack: ["ReactJS", "Node", "Tailwind", "Git"],
    colorA: "#00F5A0",
    colorB: "#00D9FF",
    position: [4, 0, 0],
    website: "https://example.com/member-2",
  },
  {
    id: "member-3",
    name: "Member 3",
    role: "Role TBD",
    bio: "Placeholder bio for the third team member.",
    techStack: ["TBD"],
    colorA: "#FF6B6B",
    colorB: "#FF8E53",
    position: [-2, 0, -1.5],
    website: "https://example.com/member-3",
  },
  {
    id: "member-4",
    name: "Member 4",
    role: "Role TBD",
    bio: "Placeholder bio for the fourth team member.",
    techStack: ["TBD"],
    colorA: "#A855F7",
    colorB: "#EC4899",
    position: [2, 0, -1.5],
    website: "https://example.com/member-4",
  },
  {
    id: "member-5",
    name: "Member 5",
    role: "Role TBD",
    bio: "Placeholder bio for the fifth team member.",
    techStack: ["TBD"],
    colorA: "#F59E0B",
    colorB: "#EF4444",
    position: [0, 0, -3],
    website: "https://example.com/member-5",
  },
];

/** @param {any} id */
export const getMemberById = (id) => TEAM.find((m) => m.id === id);